package com.example.esercizio_blog.exceptions;

import jakarta.persistence.EntityExistsException;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.ErrorResponse;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
public class ExceptionHandlerClass {

    @ExceptionHandler(value = EntityNotFoundException.class)
    protected ResponseEntity<ErrorResponse> entityNotFound(EntityNotFoundException ex) {
        ErrorResponse error = new ErrorResponse();
        error.setMessage("Entity not found");
        error.setDetails(ex.getMessage());
        error.setStatusCode(404); // Corretto da String a int
        return new ResponseEntity<>(error, HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler(value = EntityExistsException.class)
    protected ResponseEntity<ErrorResponse> alreadyExistsException(EntityExistsException ex) {
        ErrorResponse error = new ErrorResponse();
        error.setMessage("Entity already exists");
        error.setDetails(ex.getMessage());
        error.setStatusCode(409);
        return new ResponseEntity<>(error, HttpStatus.CONFLICT);
    }
}
